### PR TITLE
Made previous PR merged 5.3 compatible

### PR DESCRIPTION
**Pull request by jayelkaake**
Made previous PR merged 5.3 compatible by moving the inline function to a instance method so that it has access to the $this context. 
See http://php.net/manual/en/functions.anonymous.php
Also formatted according to http://www.php-fig.org/psr/psr-2/

### CODE REVIEW

**Comment by wbrowar** [comment]
@jayelkaake Thanks for the PR! I'll take a look at getting this updated in the next couple of days.

**Comment by jayelkaake** [comment]
_poke_ @wbrowar :smile:

**Comment by wbrowar** [comment]
So.... a couple days later... Sorry, I've been working on 1.4 and thought I'd have it up a while ago. I'll just merge it for now, but it'll also be included in 1.4. Thanks for the reminder, @jayelkaake

**Comment by jayelkaake** [comment]
Thanks!

**Pull request merged**
